/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WrappedHandleRouteImport } from './routes/wrapped.$handle'
import { Route as GlobalWrappedYearRouteImport } from './routes/global-wrapped.$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WrappedHandleRoute = WrappedHandleRouteImport.update({
  id: '/wrapped/$handle',
  path: '/wrapped/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalWrappedYearRoute = GlobalWrappedYearRouteImport.update({
  id: '/global-wrapped/$year',
  path: '/global-wrapped/$year',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/global-wrapped/$year': typeof GlobalWrappedYearRoute
  '/wrapped/$handle': typeof WrappedHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/global-wrapped/$year': typeof GlobalWrappedYearRoute
  '/wrapped/$handle': typeof WrappedHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/global-wrapped/$year': typeof GlobalWrappedYearRoute
  '/wrapped/$handle': typeof WrappedHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/global-wrapped/$year' | '/wrapped/$handle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/global-wrapped/$year' | '/wrapped/$handle'
  id: '__root__' | '/' | '/global-wrapped/$year' | '/wrapped/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlobalWrappedYearRoute: typeof GlobalWrappedYearRoute
  WrappedHandleRoute: typeof WrappedHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrapped/$handle': {
      id: '/wrapped/$handle'
      path: '/wrapped/$handle'
      fullPath: '/wrapped/$handle'
      preLoaderRoute: typeof WrappedHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-wrapped/$year': {
      id: '/global-wrapped/$year'
      path: '/global-wrapped/$year'
      fullPath: '/global-wrapped/$year'
      preLoaderRoute: typeof GlobalWrappedYearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlobalWrappedYearRoute: GlobalWrappedYearRoute,
  WrappedHandleRoute: WrappedHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
